---
# This playbook deploys the entire application, server and client.

- name: apply common configuration to all nodes
  hosts: all

  roles:
    - common

- name: set up the minion servers
  hosts: servers

  roles:
    - telep_server
