---
# Directories

- name: root deployment directory
  file: path=/var/www/telep state=directory owner=root group=deployers mode=2775
  become: yes

- name: releases directory
  file: path=/var/www/telep/releases state=directory owner=root group=deployers mode=2775
  become: yes

- name: shared directory
  file: path=/var/www/telep/shared state=directory owner=root group=deployers mode=2775
  become: yes

- name: shared config directory
  file: path=/var/www/telep/shared/config state=directory owner=root group=deployers mode=2775
  become: yes

- name: local node installation
  file: path=/usr/local/node state=directory owner=root group=deployers mode=2775
  become: yes
