---
# Tasks for all servers

- name: install mongodb
  apt: name=mongodb-server

- name: install rabbitmq
  apt: name=rabbitmq-server

- include: users.yml

- include: directories.yml

- include: rabbitmq-certificates.yml

- include: telep-certificates.yml
