---
# Tasks for all servers

- name: install mongodb
  apt: name=mongodb-server
  become: yes

- name: install rabbitmq
  apt: name=rabbitmq-server
  become: yes

- include: users.yml

- include: directories.yml

- include: rabbitmq-certificates.yml

- include: telep-certificates.yml

- include: shared-files.yml
