---
# Tasks to put the required RabbitMQ certificates on the server.

- name: RabbitMQ certificate directory
  file: path={{ rabbitmq_cert_path }} state=directory owner={{ rabbitmq_user }} group={{ rabbitmq_group }} mode=0755
  become: yes

- name: RabbitMQ private key directory
  file: path={{ rabbitmq_private_path }} state=directory owner={{ rabbitmq_user }} group={{ rabbitmq_group }} mode=0750
  become: yes

- name: install CA certificate for RabbitMQ
  copy: src={{ rabbitmq_ca_cert }} dest={{ rabbitmq_cert_path }}/{{ rabbitmq_ca_cert }} owner={{ rabbitmq_user }} group={{ rabbitmq_group }} mode=0644
  become: yes

- name: install self-signed certificate for RabbitMQ
  copy: src={{ rabbitmq_cert }} dest={{ rabbitmq_cert_path }}/{{ rabbitmq_cert }} owner={{ rabbitmq_user }} group={{ rabbitmq_group }} mode=0644
  become: yes

- name: install private key for certificate for RabbitMQ
  copy: src={{ rabbitmq_key }}.ansible dest={{ rabbitmq_private_path }}/{{ rabbitmq_key }} owner={{ rabbitmq_user }} group={{ rabbitmq_group }} mode=0640
  become: yes
