---
# Users

- name: telep user
  user: name=telep state=present system=yes shell=/bin/false
  become: yes

- name: deployers group
  group: name=deployers state=present
  become: yes

- name: dsieh user groups
  user: name=dsieh shell=/bin/bash groups=deployers append=yes
  become: yes
