---
# Tasks for the minion clients

- include: users.yml

- include: directories.yml

- name: copy node to root
  nvm_tool: action=copy node_version=v6.1.0

- include: minion-certificates.yml

- include: shared-files.yml

- include: services.yml
