---
# Common tasks for all environments

- name: install curl
  apt: name=curl state=present
  become: yes

- name: install nvm
  nvm_tool: action=install

- name: install node
  nvm_tool: action=setup node_version=v6.1.0

#- name: ping
  #ping:

#- name: what time is it
  #timetest:
